from django.db import models
class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup)
    permission = models.ForeignKey('AuthPermission')

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group_id', 'permission_id'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType')
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type_id', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser)
    group = models.ForeignKey(AuthGroup)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user_id', 'group_id'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser)
    permission = models.ForeignKey(AuthPermission)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user_id', 'permission_id'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', blank=True, null=True)
    user = models.ForeignKey(AuthUser)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Interval61000(models.Model):
    node0 = models.FloatField(blank=True, null=True)
    node1 = models.FloatField(blank=True, null=True)
    node2 = models.FloatField(blank=True, null=True)
    node3 = models.FloatField(blank=True, null=True)
    node4 = models.FloatField(blank=True, null=True)
    node5 = models.FloatField(blank=True, null=True)
    node6 = models.FloatField(blank=True, null=True)
    node7 = models.FloatField(blank=True, null=True)
    node8 = models.FloatField(blank=True, null=True)
    node9 = models.FloatField(blank=True, null=True)
    node10 = models.FloatField(blank=True, null=True)
    node11 = models.FloatField(blank=True, null=True)
    node12 = models.FloatField(blank=True, null=True)
    node13 = models.FloatField(blank=True, null=True)
    node14 = models.FloatField(blank=True, null=True)
    node15 = models.FloatField(blank=True, null=True)
    node16 = models.FloatField(blank=True, null=True)
    node17 = models.FloatField(blank=True, null=True)
    node18 = models.FloatField(blank=True, null=True)
    node19 = models.FloatField(blank=True, null=True)
    node20 = models.FloatField(blank=True, null=True)
    node21 = models.FloatField(blank=True, null=True)
    node22 = models.FloatField(blank=True, null=True)
    node23 = models.FloatField(blank=True, null=True)
    node24 = models.FloatField(blank=True, null=True)
    node25 = models.FloatField(blank=True, null=True)
    node26 = models.FloatField(blank=True, null=True)
    node27 = models.FloatField(blank=True, null=True)
    node28 = models.FloatField(blank=True, null=True)
    node29 = models.FloatField(blank=True, null=True)
    node30 = models.FloatField(blank=True, null=True)
    node31 = models.FloatField(blank=True, null=True)
    node32 = models.FloatField(blank=True, null=True)
    node33 = models.FloatField(blank=True, null=True)
    node34 = models.FloatField(blank=True, null=True)
    node35 = models.FloatField(blank=True, null=True)
    node36 = models.FloatField(blank=True, null=True)
    node37 = models.FloatField(blank=True, null=True)
    node38 = models.FloatField(blank=True, null=True)
    node39 = models.FloatField(blank=True, null=True)
    node40 = models.FloatField(blank=True, null=True)
    node41 = models.FloatField(blank=True, null=True)
    node42 = models.FloatField(blank=True, null=True)
    node43 = models.FloatField(blank=True, null=True)
    node44 = models.FloatField(blank=True, null=True)
    node45 = models.FloatField(blank=True, null=True)
    node46 = models.FloatField(blank=True, null=True)
    node47 = models.FloatField(blank=True, null=True)
    node48 = models.FloatField(blank=True, null=True)
    node49 = models.FloatField(blank=True, null=True)
    node50 = models.FloatField(blank=True, null=True)
    node51 = models.FloatField(blank=True, null=True)
    node52 = models.FloatField(blank=True, null=True)
    node53 = models.FloatField(blank=True, null=True)
    node54 = models.FloatField(blank=True, null=True)
    node55 = models.FloatField(blank=True, null=True)
    node56 = models.FloatField(blank=True, null=True)
    node57 = models.FloatField(blank=True, null=True)
    node58 = models.FloatField(blank=True, null=True)
    node59 = models.FloatField(blank=True, null=True)
    node60 = models.FloatField(blank=True, null=True)
    node61 = models.FloatField(blank=True, null=True)
    node62 = models.FloatField(blank=True, null=True)
    node63 = models.FloatField(blank=True, null=True)
    node64 = models.FloatField(blank=True, null=True)
    node65 = models.FloatField(blank=True, null=True)
    node66 = models.FloatField(blank=True, null=True)
    node67 = models.FloatField(blank=True, null=True)
    node68 = models.FloatField(blank=True, null=True)
    node69 = models.FloatField(blank=True, null=True)
    node70 = models.FloatField(blank=True, null=True)
    node71 = models.FloatField(blank=True, null=True)
    node72 = models.FloatField(blank=True, null=True)
    node73 = models.FloatField(blank=True, null=True)
    node74 = models.FloatField(blank=True, null=True)
    node75 = models.FloatField(blank=True, null=True)
    node76 = models.FloatField(blank=True, null=True)
    node77 = models.FloatField(blank=True, null=True)
    node78 = models.FloatField(blank=True, null=True)
    node79 = models.FloatField(blank=True, null=True)
    node80 = models.FloatField(blank=True, null=True)
    node81 = models.FloatField(blank=True, null=True)
    node82 = models.FloatField(blank=True, null=True)
    node83 = models.FloatField(blank=True, null=True)
    node84 = models.FloatField(blank=True, null=True)
    node85 = models.FloatField(blank=True, null=True)
    node86 = models.FloatField(blank=True, null=True)
    node87 = models.FloatField(blank=True, null=True)
    node88 = models.FloatField(blank=True, null=True)
    node89 = models.FloatField(blank=True, null=True)
    node90 = models.FloatField(blank=True, null=True)
    node91 = models.FloatField(blank=True, null=True)
    node92 = models.FloatField(blank=True, null=True)
    node93 = models.FloatField(blank=True, null=True)
    node94 = models.FloatField(blank=True, null=True)
    node95 = models.FloatField(blank=True, null=True)
    node96 = models.FloatField(blank=True, null=True)
    node97 = models.FloatField(blank=True, null=True)
    node98 = models.FloatField(blank=True, null=True)
    node99 = models.FloatField(blank=True, null=True)
    node100 = models.FloatField(blank=True, null=True)
    node101 = models.FloatField(blank=True, null=True)
    node102 = models.FloatField(blank=True, null=True)
    node103 = models.FloatField(blank=True, null=True)
    node104 = models.FloatField(blank=True, null=True)
    node105 = models.FloatField(blank=True, null=True)
    node106 = models.FloatField(blank=True, null=True)
    node107 = models.FloatField(blank=True, null=True)
    node108 = models.FloatField(blank=True, null=True)
    node109 = models.FloatField(blank=True, null=True)
    node110 = models.FloatField(blank=True, null=True)
    node111 = models.FloatField(blank=True, null=True)
    node112 = models.FloatField(blank=True, null=True)
    node113 = models.FloatField(blank=True, null=True)
    node114 = models.FloatField(blank=True, null=True)
    node115 = models.FloatField(blank=True, null=True)
    node116 = models.FloatField(blank=True, null=True)
    node117 = models.FloatField(blank=True, null=True)
    node118 = models.FloatField(blank=True, null=True)
    node119 = models.FloatField(blank=True, null=True)
    node120 = models.FloatField(blank=True, null=True)
    node121 = models.FloatField(blank=True, null=True)
    node122 = models.FloatField(blank=True, null=True)
    node123 = models.FloatField(blank=True, null=True)
    node124 = models.FloatField(blank=True, null=True)
    node125 = models.FloatField(blank=True, null=True)
    node126 = models.FloatField(blank=True, null=True)
    node127 = models.FloatField(blank=True, null=True)
    node128 = models.FloatField(blank=True, null=True)
    node129 = models.FloatField(blank=True, null=True)
    node130 = models.FloatField(blank=True, null=True)
    node131 = models.FloatField(blank=True, null=True)
    node132 = models.FloatField(blank=True, null=True)
    node133 = models.FloatField(blank=True, null=True)
    node134 = models.FloatField(blank=True, null=True)
    node135 = models.FloatField(blank=True, null=True)
    node136 = models.FloatField(blank=True, null=True)
    node137 = models.FloatField(blank=True, null=True)
    node138 = models.FloatField(blank=True, null=True)
    node139 = models.FloatField(blank=True, null=True)
    node140 = models.FloatField(blank=True, null=True)
    node141 = models.FloatField(blank=True, null=True)
    node142 = models.FloatField(blank=True, null=True)
    node143 = models.FloatField(blank=True, null=True)
    node144 = models.FloatField(blank=True, null=True)
    node145 = models.FloatField(blank=True, null=True)
    node146 = models.FloatField(blank=True, null=True)
    node147 = models.FloatField(blank=True, null=True)
    node148 = models.FloatField(blank=True, null=True)
    node149 = models.FloatField(blank=True, null=True)
    node150 = models.FloatField(blank=True, null=True)
    node151 = models.FloatField(blank=True, null=True)
    node152 = models.FloatField(blank=True, null=True)
    node153 = models.FloatField(blank=True, null=True)
    node154 = models.FloatField(blank=True, null=True)
    node155 = models.FloatField(blank=True, null=True)
    node156 = models.FloatField(blank=True, null=True)
    node157 = models.FloatField(blank=True, null=True)
    node158 = models.FloatField(blank=True, null=True)
    node159 = models.FloatField(blank=True, null=True)
    node160 = models.FloatField(blank=True, null=True)
    node161 = models.FloatField(blank=True, null=True)
    node162 = models.FloatField(blank=True, null=True)
    node163 = models.FloatField(blank=True, null=True)
    node164 = models.FloatField(blank=True, null=True)
    node165 = models.FloatField(blank=True, null=True)
    node166 = models.FloatField(blank=True, null=True)
    node167 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'interval61000'


class Interval62000(models.Model):
    node0 = models.FloatField(blank=True, null=True)
    node1 = models.FloatField(blank=True, null=True)
    node2 = models.FloatField(blank=True, null=True)
    node3 = models.FloatField(blank=True, null=True)
    node4 = models.FloatField(blank=True, null=True)
    node5 = models.FloatField(blank=True, null=True)
    node6 = models.FloatField(blank=True, null=True)
    node7 = models.FloatField(blank=True, null=True)
    node8 = models.FloatField(blank=True, null=True)
    node9 = models.FloatField(blank=True, null=True)
    node10 = models.FloatField(blank=True, null=True)
    node11 = models.FloatField(blank=True, null=True)
    node12 = models.FloatField(blank=True, null=True)
    node13 = models.FloatField(blank=True, null=True)
    node14 = models.FloatField(blank=True, null=True)
    node15 = models.FloatField(blank=True, null=True)
    node16 = models.FloatField(blank=True, null=True)
    node17 = models.FloatField(blank=True, null=True)
    node18 = models.FloatField(blank=True, null=True)
    node19 = models.FloatField(blank=True, null=True)
    node20 = models.FloatField(blank=True, null=True)
    node21 = models.FloatField(blank=True, null=True)
    node22 = models.FloatField(blank=True, null=True)
    node23 = models.FloatField(blank=True, null=True)
    node24 = models.FloatField(blank=True, null=True)
    node25 = models.FloatField(blank=True, null=True)
    node26 = models.FloatField(blank=True, null=True)
    node27 = models.FloatField(blank=True, null=True)
    node28 = models.FloatField(blank=True, null=True)
    node29 = models.FloatField(blank=True, null=True)
    node30 = models.FloatField(blank=True, null=True)
    node31 = models.FloatField(blank=True, null=True)
    node32 = models.FloatField(blank=True, null=True)
    node33 = models.FloatField(blank=True, null=True)
    node34 = models.FloatField(blank=True, null=True)
    node35 = models.FloatField(blank=True, null=True)
    node36 = models.FloatField(blank=True, null=True)
    node37 = models.FloatField(blank=True, null=True)
    node38 = models.FloatField(blank=True, null=True)
    node39 = models.FloatField(blank=True, null=True)
    node40 = models.FloatField(blank=True, null=True)
    node41 = models.FloatField(blank=True, null=True)
    node42 = models.FloatField(blank=True, null=True)
    node43 = models.FloatField(blank=True, null=True)
    node44 = models.FloatField(blank=True, null=True)
    node45 = models.FloatField(blank=True, null=True)
    node46 = models.FloatField(blank=True, null=True)
    node47 = models.FloatField(blank=True, null=True)
    node48 = models.FloatField(blank=True, null=True)
    node49 = models.FloatField(blank=True, null=True)
    node50 = models.FloatField(blank=True, null=True)
    node51 = models.FloatField(blank=True, null=True)
    node52 = models.FloatField(blank=True, null=True)
    node53 = models.FloatField(blank=True, null=True)
    node54 = models.FloatField(blank=True, null=True)
    node55 = models.FloatField(blank=True, null=True)
    node56 = models.FloatField(blank=True, null=True)
    node57 = models.FloatField(blank=True, null=True)
    node58 = models.FloatField(blank=True, null=True)
    node59 = models.FloatField(blank=True, null=True)
    node60 = models.FloatField(blank=True, null=True)
    node61 = models.FloatField(blank=True, null=True)
    node62 = models.FloatField(blank=True, null=True)
    node63 = models.FloatField(blank=True, null=True)
    node64 = models.FloatField(blank=True, null=True)
    node65 = models.FloatField(blank=True, null=True)
    node66 = models.FloatField(blank=True, null=True)
    node67 = models.FloatField(blank=True, null=True)
    node68 = models.FloatField(blank=True, null=True)
    node69 = models.FloatField(blank=True, null=True)
    node70 = models.FloatField(blank=True, null=True)
    node71 = models.FloatField(blank=True, null=True)
    node72 = models.FloatField(blank=True, null=True)
    node73 = models.FloatField(blank=True, null=True)
    node74 = models.FloatField(blank=True, null=True)
    node75 = models.FloatField(blank=True, null=True)
    node76 = models.FloatField(blank=True, null=True)
    node77 = models.FloatField(blank=True, null=True)
    node78 = models.FloatField(blank=True, null=True)
    node79 = models.FloatField(blank=True, null=True)
    node80 = models.FloatField(blank=True, null=True)
    node81 = models.FloatField(blank=True, null=True)
    node82 = models.FloatField(blank=True, null=True)
    node83 = models.FloatField(blank=True, null=True)
    node84 = models.FloatField(blank=True, null=True)
    node85 = models.FloatField(blank=True, null=True)
    node86 = models.FloatField(blank=True, null=True)
    node87 = models.FloatField(blank=True, null=True)
    node88 = models.FloatField(blank=True, null=True)
    node89 = models.FloatField(blank=True, null=True)
    node90 = models.FloatField(blank=True, null=True)
    node91 = models.FloatField(blank=True, null=True)
    node92 = models.FloatField(blank=True, null=True)
    node93 = models.FloatField(blank=True, null=True)
    node94 = models.FloatField(blank=True, null=True)
    node95 = models.FloatField(blank=True, null=True)
    node96 = models.FloatField(blank=True, null=True)
    node97 = models.FloatField(blank=True, null=True)
    node98 = models.FloatField(blank=True, null=True)
    node99 = models.FloatField(blank=True, null=True)
    node100 = models.FloatField(blank=True, null=True)
    node101 = models.FloatField(blank=True, null=True)
    node102 = models.FloatField(blank=True, null=True)
    node103 = models.FloatField(blank=True, null=True)
    node104 = models.FloatField(blank=True, null=True)
    node105 = models.FloatField(blank=True, null=True)
    node106 = models.FloatField(blank=True, null=True)
    node107 = models.FloatField(blank=True, null=True)
    node108 = models.FloatField(blank=True, null=True)
    node109 = models.FloatField(blank=True, null=True)
    node110 = models.FloatField(blank=True, null=True)
    node111 = models.FloatField(blank=True, null=True)
    node112 = models.FloatField(blank=True, null=True)
    node113 = models.FloatField(blank=True, null=True)
    node114 = models.FloatField(blank=True, null=True)
    node115 = models.FloatField(blank=True, null=True)
    node116 = models.FloatField(blank=True, null=True)
    node117 = models.FloatField(blank=True, null=True)
    node118 = models.FloatField(blank=True, null=True)
    node119 = models.FloatField(blank=True, null=True)
    node120 = models.FloatField(blank=True, null=True)
    node121 = models.FloatField(blank=True, null=True)
    node122 = models.FloatField(blank=True, null=True)
    node123 = models.FloatField(blank=True, null=True)
    node124 = models.FloatField(blank=True, null=True)
    node125 = models.FloatField(blank=True, null=True)
    node126 = models.FloatField(blank=True, null=True)
    node127 = models.FloatField(blank=True, null=True)
    node128 = models.FloatField(blank=True, null=True)
    node129 = models.FloatField(blank=True, null=True)
    node130 = models.FloatField(blank=True, null=True)
    node131 = models.FloatField(blank=True, null=True)
    node132 = models.FloatField(blank=True, null=True)
    node133 = models.FloatField(blank=True, null=True)
    node134 = models.FloatField(blank=True, null=True)
    node135 = models.FloatField(blank=True, null=True)
    node136 = models.FloatField(blank=True, null=True)
    node137 = models.FloatField(blank=True, null=True)
    node138 = models.FloatField(blank=True, null=True)
    node139 = models.FloatField(blank=True, null=True)
    node140 = models.FloatField(blank=True, null=True)
    node141 = models.FloatField(blank=True, null=True)
    node142 = models.FloatField(blank=True, null=True)
    node143 = models.FloatField(blank=True, null=True)
    node144 = models.FloatField(blank=True, null=True)
    node145 = models.FloatField(blank=True, null=True)
    node146 = models.FloatField(blank=True, null=True)
    node147 = models.FloatField(blank=True, null=True)
    node148 = models.FloatField(blank=True, null=True)
    node149 = models.FloatField(blank=True, null=True)
    node150 = models.FloatField(blank=True, null=True)
    node151 = models.FloatField(blank=True, null=True)
    node152 = models.FloatField(blank=True, null=True)
    node153 = models.FloatField(blank=True, null=True)
    node154 = models.FloatField(blank=True, null=True)
    node155 = models.FloatField(blank=True, null=True)
    node156 = models.FloatField(blank=True, null=True)
    node157 = models.FloatField(blank=True, null=True)
    node158 = models.FloatField(blank=True, null=True)
    node159 = models.FloatField(blank=True, null=True)
    node160 = models.FloatField(blank=True, null=True)
    node161 = models.FloatField(blank=True, null=True)
    node162 = models.FloatField(blank=True, null=True)
    node163 = models.FloatField(blank=True, null=True)
    node164 = models.FloatField(blank=True, null=True)
    node165 = models.FloatField(blank=True, null=True)
    node166 = models.FloatField(blank=True, null=True)
    node167 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'interval62000'


class Interval6500(models.Model):
    node0 = models.FloatField(blank=True, null=True)
    node1 = models.FloatField(blank=True, null=True)
    node2 = models.FloatField(blank=True, null=True)
    node3 = models.FloatField(blank=True, null=True)
    node4 = models.FloatField(blank=True, null=True)
    node5 = models.FloatField(blank=True, null=True)
    node6 = models.FloatField(blank=True, null=True)
    node7 = models.FloatField(blank=True, null=True)
    node8 = models.FloatField(blank=True, null=True)
    node9 = models.FloatField(blank=True, null=True)
    node10 = models.FloatField(blank=True, null=True)
    node11 = models.FloatField(blank=True, null=True)
    node12 = models.FloatField(blank=True, null=True)
    node13 = models.FloatField(blank=True, null=True)
    node14 = models.FloatField(blank=True, null=True)
    node15 = models.FloatField(blank=True, null=True)
    node16 = models.FloatField(blank=True, null=True)
    node17 = models.FloatField(blank=True, null=True)
    node18 = models.FloatField(blank=True, null=True)
    node19 = models.FloatField(blank=True, null=True)
    node20 = models.FloatField(blank=True, null=True)
    node21 = models.FloatField(blank=True, null=True)
    node22 = models.FloatField(blank=True, null=True)
    node23 = models.FloatField(blank=True, null=True)
    node24 = models.FloatField(blank=True, null=True)
    node25 = models.FloatField(blank=True, null=True)
    node26 = models.FloatField(blank=True, null=True)
    node27 = models.FloatField(blank=True, null=True)
    node28 = models.FloatField(blank=True, null=True)
    node29 = models.FloatField(blank=True, null=True)
    node30 = models.FloatField(blank=True, null=True)
    node31 = models.FloatField(blank=True, null=True)
    node32 = models.FloatField(blank=True, null=True)
    node33 = models.FloatField(blank=True, null=True)
    node34 = models.FloatField(blank=True, null=True)
    node35 = models.FloatField(blank=True, null=True)
    node36 = models.FloatField(blank=True, null=True)
    node37 = models.FloatField(blank=True, null=True)
    node38 = models.FloatField(blank=True, null=True)
    node39 = models.FloatField(blank=True, null=True)
    node40 = models.FloatField(blank=True, null=True)
    node41 = models.FloatField(blank=True, null=True)
    node42 = models.FloatField(blank=True, null=True)
    node43 = models.FloatField(blank=True, null=True)
    node44 = models.FloatField(blank=True, null=True)
    node45 = models.FloatField(blank=True, null=True)
    node46 = models.FloatField(blank=True, null=True)
    node47 = models.FloatField(blank=True, null=True)
    node48 = models.FloatField(blank=True, null=True)
    node49 = models.FloatField(blank=True, null=True)
    node50 = models.FloatField(blank=True, null=True)
    node51 = models.FloatField(blank=True, null=True)
    node52 = models.FloatField(blank=True, null=True)
    node53 = models.FloatField(blank=True, null=True)
    node54 = models.FloatField(blank=True, null=True)
    node55 = models.FloatField(blank=True, null=True)
    node56 = models.FloatField(blank=True, null=True)
    node57 = models.FloatField(blank=True, null=True)
    node58 = models.FloatField(blank=True, null=True)
    node59 = models.FloatField(blank=True, null=True)
    node60 = models.FloatField(blank=True, null=True)
    node61 = models.FloatField(blank=True, null=True)
    node62 = models.FloatField(blank=True, null=True)
    node63 = models.FloatField(blank=True, null=True)
    node64 = models.FloatField(blank=True, null=True)
    node65 = models.FloatField(blank=True, null=True)
    node66 = models.FloatField(blank=True, null=True)
    node67 = models.FloatField(blank=True, null=True)
    node68 = models.FloatField(blank=True, null=True)
    node69 = models.FloatField(blank=True, null=True)
    node70 = models.FloatField(blank=True, null=True)
    node71 = models.FloatField(blank=True, null=True)
    node72 = models.FloatField(blank=True, null=True)
    node73 = models.FloatField(blank=True, null=True)
    node74 = models.FloatField(blank=True, null=True)
    node75 = models.FloatField(blank=True, null=True)
    node76 = models.FloatField(blank=True, null=True)
    node77 = models.FloatField(blank=True, null=True)
    node78 = models.FloatField(blank=True, null=True)
    node79 = models.FloatField(blank=True, null=True)
    node80 = models.FloatField(blank=True, null=True)
    node81 = models.FloatField(blank=True, null=True)
    node82 = models.FloatField(blank=True, null=True)
    node83 = models.FloatField(blank=True, null=True)
    node84 = models.FloatField(blank=True, null=True)
    node85 = models.FloatField(blank=True, null=True)
    node86 = models.FloatField(blank=True, null=True)
    node87 = models.FloatField(blank=True, null=True)
    node88 = models.FloatField(blank=True, null=True)
    node89 = models.FloatField(blank=True, null=True)
    node90 = models.FloatField(blank=True, null=True)
    node91 = models.FloatField(blank=True, null=True)
    node92 = models.FloatField(blank=True, null=True)
    node93 = models.FloatField(blank=True, null=True)
    node94 = models.FloatField(blank=True, null=True)
    node95 = models.FloatField(blank=True, null=True)
    node96 = models.FloatField(blank=True, null=True)
    node97 = models.FloatField(blank=True, null=True)
    node98 = models.FloatField(blank=True, null=True)
    node99 = models.FloatField(blank=True, null=True)
    node100 = models.FloatField(blank=True, null=True)
    node101 = models.FloatField(blank=True, null=True)
    node102 = models.FloatField(blank=True, null=True)
    node103 = models.FloatField(blank=True, null=True)
    node104 = models.FloatField(blank=True, null=True)
    node105 = models.FloatField(blank=True, null=True)
    node106 = models.FloatField(blank=True, null=True)
    node107 = models.FloatField(blank=True, null=True)
    node108 = models.FloatField(blank=True, null=True)
    node109 = models.FloatField(blank=True, null=True)
    node110 = models.FloatField(blank=True, null=True)
    node111 = models.FloatField(blank=True, null=True)
    node112 = models.FloatField(blank=True, null=True)
    node113 = models.FloatField(blank=True, null=True)
    node114 = models.FloatField(blank=True, null=True)
    node115 = models.FloatField(blank=True, null=True)
    node116 = models.FloatField(blank=True, null=True)
    node117 = models.FloatField(blank=True, null=True)
    node118 = models.FloatField(blank=True, null=True)
    node119 = models.FloatField(blank=True, null=True)
    node120 = models.FloatField(blank=True, null=True)
    node121 = models.FloatField(blank=True, null=True)
    node122 = models.FloatField(blank=True, null=True)
    node123 = models.FloatField(blank=True, null=True)
    node124 = models.FloatField(blank=True, null=True)
    node125 = models.FloatField(blank=True, null=True)
    node126 = models.FloatField(blank=True, null=True)
    node127 = models.FloatField(blank=True, null=True)
    node128 = models.FloatField(blank=True, null=True)
    node129 = models.FloatField(blank=True, null=True)
    node130 = models.FloatField(blank=True, null=True)
    node131 = models.FloatField(blank=True, null=True)
    node132 = models.FloatField(blank=True, null=True)
    node133 = models.FloatField(blank=True, null=True)
    node134 = models.FloatField(blank=True, null=True)
    node135 = models.FloatField(blank=True, null=True)
    node136 = models.FloatField(blank=True, null=True)
    node137 = models.FloatField(blank=True, null=True)
    node138 = models.FloatField(blank=True, null=True)
    node139 = models.FloatField(blank=True, null=True)
    node140 = models.FloatField(blank=True, null=True)
    node141 = models.FloatField(blank=True, null=True)
    node142 = models.FloatField(blank=True, null=True)
    node143 = models.FloatField(blank=True, null=True)
    node144 = models.FloatField(blank=True, null=True)
    node145 = models.FloatField(blank=True, null=True)
    node146 = models.FloatField(blank=True, null=True)
    node147 = models.FloatField(blank=True, null=True)
    node148 = models.FloatField(blank=True, null=True)
    node149 = models.FloatField(blank=True, null=True)
    node150 = models.FloatField(blank=True, null=True)
    node151 = models.FloatField(blank=True, null=True)
    node152 = models.FloatField(blank=True, null=True)
    node153 = models.FloatField(blank=True, null=True)
    node154 = models.FloatField(blank=True, null=True)
    node155 = models.FloatField(blank=True, null=True)
    node156 = models.FloatField(blank=True, null=True)
    node157 = models.FloatField(blank=True, null=True)
    node158 = models.FloatField(blank=True, null=True)
    node159 = models.FloatField(blank=True, null=True)
    node160 = models.FloatField(blank=True, null=True)
    node161 = models.FloatField(blank=True, null=True)
    node162 = models.FloatField(blank=True, null=True)
    node163 = models.FloatField(blank=True, null=True)
    node164 = models.FloatField(blank=True, null=True)
    node165 = models.FloatField(blank=True, null=True)
    node166 = models.FloatField(blank=True, null=True)
    node167 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'interval6500'


class MulticastSimulatorNode(models.Model):
    pdr = models.FloatField()

    class Meta:
        managed = False
        db_table = 'multicast_simulator_node'


class Sixmbps(models.Model):
    node0 = models.BooleanField()
    node1 = models.BooleanField()
    node2 = models.BooleanField()
    node3 = models.BooleanField()
    node4 = models.BooleanField()
    node5 = models.BooleanField()
    node6 = models.BooleanField()
    node7 = models.BooleanField()
    node8 = models.BooleanField()
    node9 = models.BooleanField()
    node10 = models.BooleanField()
    node11 = models.BooleanField()
    node12 = models.BooleanField()
    node13 = models.BooleanField()
    node14 = models.BooleanField()
    node15 = models.BooleanField()
    node16 = models.BooleanField()
    node17 = models.BooleanField()
    node18 = models.BooleanField()
    node19 = models.BooleanField()
    node20 = models.BooleanField()
    node21 = models.BooleanField()
    node22 = models.BooleanField()
    node23 = models.BooleanField()
    node24 = models.BooleanField()
    node25 = models.BooleanField()
    node26 = models.BooleanField()
    node27 = models.BooleanField()
    node28 = models.BooleanField()
    node29 = models.BooleanField()
    node30 = models.BooleanField()
    node31 = models.BooleanField()
    node32 = models.BooleanField()
    node33 = models.BooleanField()
    node34 = models.BooleanField()
    node35 = models.BooleanField()
    node36 = models.BooleanField()
    node37 = models.BooleanField()
    node38 = models.BooleanField()
    node39 = models.BooleanField()
    node40 = models.BooleanField()
    node41 = models.BooleanField()
    node42 = models.BooleanField()
    node43 = models.BooleanField()
    node44 = models.BooleanField()
    node45 = models.BooleanField()
    node46 = models.BooleanField()
    node47 = models.BooleanField()
    node48 = models.BooleanField()
    node49 = models.BooleanField()
    node50 = models.BooleanField()
    node51 = models.BooleanField()
    node52 = models.BooleanField()
    node53 = models.BooleanField()
    node54 = models.BooleanField()
    node55 = models.BooleanField()
    node56 = models.BooleanField()
    node57 = models.BooleanField()
    node58 = models.BooleanField()
    node59 = models.BooleanField()
    node60 = models.BooleanField()
    node61 = models.BooleanField()
    node62 = models.BooleanField()
    node63 = models.BooleanField()
    node64 = models.BooleanField()
    node65 = models.BooleanField()
    node66 = models.BooleanField()
    node67 = models.BooleanField()
    node68 = models.BooleanField()
    node69 = models.BooleanField()
    node70 = models.BooleanField()
    node71 = models.BooleanField()
    node72 = models.BooleanField()
    node73 = models.BooleanField()
    node74 = models.BooleanField()
    node75 = models.BooleanField()
    node76 = models.BooleanField()
    node77 = models.BooleanField()
    node78 = models.BooleanField()
    node79 = models.BooleanField()
    node80 = models.BooleanField()
    node81 = models.BooleanField()
    node82 = models.BooleanField()
    node83 = models.BooleanField()
    node84 = models.BooleanField()
    node85 = models.BooleanField()
    node86 = models.BooleanField()
    node87 = models.BooleanField()
    node88 = models.BooleanField()
    node89 = models.BooleanField()
    node90 = models.BooleanField()
    node91 = models.BooleanField()
    node92 = models.BooleanField()
    node93 = models.BooleanField()
    node94 = models.BooleanField()
    node95 = models.BooleanField()
    node96 = models.BooleanField()
    node97 = models.BooleanField()
    node98 = models.BooleanField()
    node99 = models.BooleanField()
    node100 = models.BooleanField()
    node101 = models.BooleanField()
    node102 = models.BooleanField()
    node103 = models.BooleanField()
    node104 = models.BooleanField()
    node105 = models.BooleanField()
    node106 = models.BooleanField()
    node107 = models.BooleanField()
    node108 = models.BooleanField()
    node109 = models.BooleanField()
    node110 = models.BooleanField()
    node111 = models.BooleanField()
    node112 = models.BooleanField()
    node113 = models.BooleanField()
    node114 = models.BooleanField()
    node115 = models.BooleanField()
    node116 = models.BooleanField()
    node117 = models.BooleanField()
    node118 = models.BooleanField()
    node119 = models.BooleanField()
    node120 = models.BooleanField()
    node121 = models.BooleanField()
    node122 = models.BooleanField()
    node123 = models.BooleanField()
    node124 = models.BooleanField()
    node125 = models.BooleanField()
    node126 = models.BooleanField()
    node127 = models.BooleanField()
    node128 = models.BooleanField()
    node129 = models.BooleanField()
    node130 = models.BooleanField()
    node131 = models.BooleanField()
    node132 = models.BooleanField()
    node133 = models.BooleanField()
    node134 = models.BooleanField()
    node135 = models.BooleanField()
    node136 = models.BooleanField()
    node137 = models.BooleanField()
    node138 = models.BooleanField()
    node139 = models.BooleanField()
    node140 = models.BooleanField()
    node141 = models.BooleanField()
    node142 = models.BooleanField()
    node143 = models.BooleanField()
    node144 = models.BooleanField()
    node145 = models.BooleanField()
    node146 = models.BooleanField()
    node147 = models.BooleanField()
    node148 = models.BooleanField()
    node149 = models.BooleanField()
    node150 = models.BooleanField()
    node151 = models.BooleanField()
    node152 = models.BooleanField()
    node153 = models.BooleanField()
    node154 = models.BooleanField()
    node155 = models.BooleanField()
    node156 = models.BooleanField()
    node157 = models.BooleanField()
    node158 = models.BooleanField()
    node159 = models.BooleanField()
    node160 = models.BooleanField()
    node161 = models.BooleanField()
    node162 = models.BooleanField()
    node163 = models.BooleanField()
    node164 = models.BooleanField()
    node165 = models.BooleanField()
    node166 = models.BooleanField()
    node167 = models.BooleanField()
    node168 = models.BooleanField()
    node169 = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'sixmbps'


class Sixmbpsorder(models.Model):
    node0 = models.CharField(max_length=5, blank=True, null=True)
    node1 = models.CharField(max_length=5, blank=True, null=True)
    node2 = models.CharField(max_length=5, blank=True, null=True)
    node3 = models.CharField(max_length=5, blank=True, null=True)
    node4 = models.CharField(max_length=5, blank=True, null=True)
    node5 = models.CharField(max_length=5, blank=True, null=True)
    node6 = models.CharField(max_length=5, blank=True, null=True)
    node7 = models.CharField(max_length=5, blank=True, null=True)
    node8 = models.CharField(max_length=5, blank=True, null=True)
    node9 = models.CharField(max_length=5, blank=True, null=True)
    node10 = models.CharField(max_length=5, blank=True, null=True)
    node11 = models.CharField(max_length=5, blank=True, null=True)
    node12 = models.CharField(max_length=5, blank=True, null=True)
    node13 = models.CharField(max_length=5, blank=True, null=True)
    node14 = models.CharField(max_length=5, blank=True, null=True)
    node15 = models.CharField(max_length=5, blank=True, null=True)
    node16 = models.CharField(max_length=5, blank=True, null=True)
    node17 = models.CharField(max_length=5, blank=True, null=True)
    node18 = models.CharField(max_length=5, blank=True, null=True)
    node19 = models.CharField(max_length=5, blank=True, null=True)
    node20 = models.CharField(max_length=5, blank=True, null=True)
    node21 = models.CharField(max_length=5, blank=True, null=True)
    node22 = models.CharField(max_length=5, blank=True, null=True)
    node23 = models.CharField(max_length=5, blank=True, null=True)
    node24 = models.CharField(max_length=5, blank=True, null=True)
    node25 = models.CharField(max_length=5, blank=True, null=True)
    node26 = models.CharField(max_length=5, blank=True, null=True)
    node27 = models.CharField(max_length=5, blank=True, null=True)
    node28 = models.CharField(max_length=5, blank=True, null=True)
    node29 = models.CharField(max_length=5, blank=True, null=True)
    node30 = models.CharField(max_length=5, blank=True, null=True)
    node31 = models.CharField(max_length=5, blank=True, null=True)
    node32 = models.CharField(max_length=5, blank=True, null=True)
    node33 = models.CharField(max_length=5, blank=True, null=True)
    node34 = models.CharField(max_length=5, blank=True, null=True)
    node35 = models.CharField(max_length=5, blank=True, null=True)
    node36 = models.CharField(max_length=5, blank=True, null=True)
    node37 = models.CharField(max_length=5, blank=True, null=True)
    node38 = models.CharField(max_length=5, blank=True, null=True)
    node39 = models.CharField(max_length=5, blank=True, null=True)
    node40 = models.CharField(max_length=5, blank=True, null=True)
    node41 = models.CharField(max_length=5, blank=True, null=True)
    node42 = models.CharField(max_length=5, blank=True, null=True)
    node43 = models.CharField(max_length=5, blank=True, null=True)
    node44 = models.CharField(max_length=5, blank=True, null=True)
    node45 = models.CharField(max_length=5, blank=True, null=True)
    node46 = models.CharField(max_length=5, blank=True, null=True)
    node47 = models.CharField(max_length=5, blank=True, null=True)
    node48 = models.CharField(max_length=5, blank=True, null=True)
    node49 = models.CharField(max_length=5, blank=True, null=True)
    node50 = models.CharField(max_length=5, blank=True, null=True)
    node51 = models.CharField(max_length=5, blank=True, null=True)
    node52 = models.CharField(max_length=5, blank=True, null=True)
    node53 = models.CharField(max_length=5, blank=True, null=True)
    node54 = models.CharField(max_length=5, blank=True, null=True)
    node55 = models.CharField(max_length=5, blank=True, null=True)
    node56 = models.CharField(max_length=5, blank=True, null=True)
    node57 = models.CharField(max_length=5, blank=True, null=True)
    node58 = models.CharField(max_length=5, blank=True, null=True)
    node59 = models.CharField(max_length=5, blank=True, null=True)
    node60 = models.CharField(max_length=5, blank=True, null=True)
    node61 = models.CharField(max_length=5, blank=True, null=True)
    node62 = models.CharField(max_length=5, blank=True, null=True)
    node63 = models.CharField(max_length=5, blank=True, null=True)
    node64 = models.CharField(max_length=5, blank=True, null=True)
    node65 = models.CharField(max_length=5, blank=True, null=True)
    node66 = models.CharField(max_length=5, blank=True, null=True)
    node67 = models.CharField(max_length=5, blank=True, null=True)
    node68 = models.CharField(max_length=5, blank=True, null=True)
    node69 = models.CharField(max_length=5, blank=True, null=True)
    node70 = models.CharField(max_length=5, blank=True, null=True)
    node71 = models.CharField(max_length=5, blank=True, null=True)
    node72 = models.CharField(max_length=5, blank=True, null=True)
    node73 = models.CharField(max_length=5, blank=True, null=True)
    node74 = models.CharField(max_length=5, blank=True, null=True)
    node75 = models.CharField(max_length=5, blank=True, null=True)
    node76 = models.CharField(max_length=5, blank=True, null=True)
    node77 = models.CharField(max_length=5, blank=True, null=True)
    node78 = models.CharField(max_length=5, blank=True, null=True)
    node79 = models.CharField(max_length=5, blank=True, null=True)
    node80 = models.CharField(max_length=5, blank=True, null=True)
    node81 = models.CharField(max_length=5, blank=True, null=True)
    node82 = models.CharField(max_length=5, blank=True, null=True)
    node83 = models.CharField(max_length=5, blank=True, null=True)
    node84 = models.CharField(max_length=5, blank=True, null=True)
    node85 = models.CharField(max_length=5, blank=True, null=True)
    node86 = models.CharField(max_length=5, blank=True, null=True)
    node87 = models.CharField(max_length=5, blank=True, null=True)
    node88 = models.CharField(max_length=5, blank=True, null=True)
    node89 = models.CharField(max_length=5, blank=True, null=True)
    node90 = models.CharField(max_length=5, blank=True, null=True)
    node91 = models.CharField(max_length=5, blank=True, null=True)
    node92 = models.CharField(max_length=5, blank=True, null=True)
    node93 = models.CharField(max_length=5, blank=True, null=True)
    node94 = models.CharField(max_length=5, blank=True, null=True)
    node95 = models.CharField(max_length=5, blank=True, null=True)
    node96 = models.CharField(max_length=5, blank=True, null=True)
    node97 = models.CharField(max_length=5, blank=True, null=True)
    node98 = models.CharField(max_length=5, blank=True, null=True)
    node99 = models.CharField(max_length=5, blank=True, null=True)
    node100 = models.CharField(max_length=5, blank=True, null=True)
    node101 = models.CharField(max_length=5, blank=True, null=True)
    node102 = models.CharField(max_length=5, blank=True, null=True)
    node103 = models.CharField(max_length=5, blank=True, null=True)
    node104 = models.CharField(max_length=5, blank=True, null=True)
    node105 = models.CharField(max_length=5, blank=True, null=True)
    node106 = models.CharField(max_length=5, blank=True, null=True)
    node107 = models.CharField(max_length=5, blank=True, null=True)
    node108 = models.CharField(max_length=5, blank=True, null=True)
    node109 = models.CharField(max_length=5, blank=True, null=True)
    node110 = models.CharField(max_length=5, blank=True, null=True)
    node111 = models.CharField(max_length=5, blank=True, null=True)
    node112 = models.CharField(max_length=5, blank=True, null=True)
    node113 = models.CharField(max_length=5, blank=True, null=True)
    node114 = models.CharField(max_length=5, blank=True, null=True)
    node115 = models.CharField(max_length=5, blank=True, null=True)
    node116 = models.CharField(max_length=5, blank=True, null=True)
    node117 = models.CharField(max_length=5, blank=True, null=True)
    node118 = models.CharField(max_length=5, blank=True, null=True)
    node119 = models.CharField(max_length=5, blank=True, null=True)
    node120 = models.CharField(max_length=5, blank=True, null=True)
    node121 = models.CharField(max_length=5, blank=True, null=True)
    node122 = models.CharField(max_length=5, blank=True, null=True)
    node123 = models.CharField(max_length=5, blank=True, null=True)
    node124 = models.CharField(max_length=5, blank=True, null=True)
    node125 = models.CharField(max_length=5, blank=True, null=True)
    node126 = models.CharField(max_length=5, blank=True, null=True)
    node127 = models.CharField(max_length=5, blank=True, null=True)
    node128 = models.CharField(max_length=5, blank=True, null=True)
    node129 = models.CharField(max_length=5, blank=True, null=True)
    node130 = models.CharField(max_length=5, blank=True, null=True)
    node131 = models.CharField(max_length=5, blank=True, null=True)
    node132 = models.CharField(max_length=5, blank=True, null=True)
    node133 = models.CharField(max_length=5, blank=True, null=True)
    node134 = models.CharField(max_length=5, blank=True, null=True)
    node135 = models.CharField(max_length=5, blank=True, null=True)
    node136 = models.CharField(max_length=5, blank=True, null=True)
    node137 = models.CharField(max_length=5, blank=True, null=True)
    node138 = models.CharField(max_length=5, blank=True, null=True)
    node139 = models.CharField(max_length=5, blank=True, null=True)
    node140 = models.CharField(max_length=5, blank=True, null=True)
    node141 = models.CharField(max_length=5, blank=True, null=True)
    node142 = models.CharField(max_length=5, blank=True, null=True)
    node143 = models.CharField(max_length=5, blank=True, null=True)
    node144 = models.CharField(max_length=5, blank=True, null=True)
    node145 = models.CharField(max_length=5, blank=True, null=True)
    node146 = models.CharField(max_length=5, blank=True, null=True)
    node147 = models.CharField(max_length=5, blank=True, null=True)
    node148 = models.CharField(max_length=5, blank=True, null=True)
    node149 = models.CharField(max_length=5, blank=True, null=True)
    node150 = models.CharField(max_length=5, blank=True, null=True)
    node151 = models.CharField(max_length=5, blank=True, null=True)
    node152 = models.CharField(max_length=5, blank=True, null=True)
    node153 = models.CharField(max_length=5, blank=True, null=True)
    node154 = models.CharField(max_length=5, blank=True, null=True)
    node155 = models.CharField(max_length=5, blank=True, null=True)
    node156 = models.CharField(max_length=5, blank=True, null=True)
    node157 = models.CharField(max_length=5, blank=True, null=True)
    node158 = models.CharField(max_length=5, blank=True, null=True)
    node159 = models.CharField(max_length=5, blank=True, null=True)
    node160 = models.CharField(max_length=5, blank=True, null=True)
    node161 = models.CharField(max_length=5, blank=True, null=True)
    node162 = models.CharField(max_length=5, blank=True, null=True)
    node163 = models.CharField(max_length=5, blank=True, null=True)
    node164 = models.CharField(max_length=5, blank=True, null=True)
    node165 = models.CharField(max_length=5, blank=True, null=True)
    node166 = models.CharField(max_length=5, blank=True, null=True)
    node167 = models.CharField(max_length=5, blank=True, null=True)
    node168 = models.CharField(max_length=5, blank=True, null=True)
    node169 = models.CharField(max_length=5, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'sixmbpsorder'
class Intervals(models.Model)
	Intervals = models.integer

class Node(models.Model):
	name_number = models.CharField(max_length=10)
	booleans = models.foreignKey(Sixmbps)
	
	avgIntervals





